main: me.pokemichele.logdel8.LogDel8
name: LogDel8
version: 1.0
author: PokeMichele
description: Log File Remover
api-version: 1.16
commands: 
   logdel:
    description: Delete Logs Manually
    aliases: [logd, dlogs]